(function(){
 const products=window.PRODUCTOS||[];
 let cart=[]; try{cart=JSON.parse(localStorage.getItem("awsCart")||"[]")}catch{}
 if(!Array.isArray(cart))cart=[];
 cart=cart.filter(item=>products.some(p=>String(p.id)===String(item.id)));
 localStorage.setItem("awsCart",JSON.stringify(cart));
 const storedCode=()=>String(localStorage.getItem("awsCountryCode")||"AR").toUpperCase();
 let countryCode=storedCode(), foreign=countryCode!=="AR", arsPerUsd=null, paypalConfigured=false;
 function unitPriceARS(p){return foreign?Number(p.foreignPriceARS||Number(p.basePriceARS||0)*2):Number(p.basePriceARS||0)}
 function moneyARS(v){return new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(v)}
 function moneyUSD(v){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2}).format(v)}
 function displayMoney(v){return foreign&&Number.isFinite(arsPerUsd)&&arsPerUsd>0?moneyUSD(v/arsPerUsd):moneyARS(v)}
 function totals(){let subtotal=0,grams=0;for(const item of cart){const p=products.find(x=>String(x.id)===String(item.id));if(!p)continue;const q=Math.max(1,Number(item.quantity)||1);subtotal+=unitPriceARS(p)*q;grams+=Math.max(1,Number(p.weightGrams)||500)*q}let shipping=0;try{shipping=cart.length?window.AWS_SHIPPING.shippingARS(countryCode,grams):0}catch(e){shipping=0}return{subtotal,shipping,total:subtotal+shipping,grams}}
 function save(){cart=cart.map(i=>({...i,quantity:Math.max(1,Number(i.quantity)||1)}));localStorage.setItem("awsCart",JSON.stringify(cart));localStorage.setItem("awsCartCount",String(cart.reduce((s,i)=>s+(Number(i.quantity)||1),0)));window.dispatchEvent(new Event("aws-cart-updated"));render();updateCheckoutState()}
 function render(){countryCode=String(document.getElementById('shipCountry')?.value||storedCode()).toUpperCase();foreign=countryCode!=="AR";const wrap=document.getElementById("cartItems"),count=cart.reduce((s,i)=>s+(Number(i.quantity)||1),0);document.getElementById("cartProductCount").textContent=count;document.getElementById("summaryCount").textContent=count;document.querySelectorAll("#cartCount").forEach(e=>e.textContent=count);const info=document.getElementById("paymentProviderInfo");if(info)info.textContent=foreign?`Pago internacional con PayPal · Envío calculado para ${countryCode}`:"Pago en Argentina con Mercado Pago · Envío fijo por pedido";
 if(!cart.length){updateCheckoutState();wrap.innerHTML='<div class="empty-cart"><h2>Tu carrito está vacío</h2><p>Elegí productos para comenzar.</p><a class="checkout-btn" href="index.html#destacados">Ver productos</a></div>';['cartSubtotal','cartShipping','cartTotal'].forEach(id=>document.getElementById(id).textContent=displayMoney(0));return}
 wrap.innerHTML=cart.map((item,index)=>{const p=products.find(x=>String(x.id)===String(item.id));if(!p)return'';const minimum=Math.max(1,Number(p.minPurchaseQuantity)||1),q=Math.max(minimum,Number(item.quantity)||minimum),price=unitPriceARS(p);return `<article class="cart-item"><img src="Fotos/${p.subcategory}/${p.images[0]}" onerror="this.src='assets/logo-argentina-world-store.jpeg'" alt="${p.name}"><div><h3>${p.name}</h3><p>CANTIDAD: <input data-index="${index}" class="cart-qty" type="number" min="${minimum}" value="${q}"></p><strong>${displayMoney(price)}</strong>${item.color?`<p><b>Color:</b> ${item.color}</p>`:''}${item.size?`<p><b>Talle:</b> ${item.size}</p>`:''}</div><button class="cart-remove" data-index="${index}">×</button></article>`}).join('');
 const t=totals();document.getElementById("cartSubtotal").textContent=displayMoney(t.subtotal);document.getElementById("cartShipping").textContent=displayMoney(t.shipping);document.getElementById("cartTotal").textContent=displayMoney(t.total);
 document.querySelectorAll('.cart-qty').forEach(input=>input.onchange=()=>{const i=Number(input.dataset.index),p=products.find(x=>String(x.id)===String(cart[i].id)),m=Math.max(1,Number(p?.minPurchaseQuantity)||1);cart[i].quantity=Math.max(m,Number(input.value)||m);save()});document.querySelectorAll('.cart-remove').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.index),1);save()});}
 const countries=[['AR','Argentina'],['BO','Bolivia'],['BR','Brasil'],['CL','Chile'],['PY','Paraguay'],['UY','Uruguay'],['CO','Colombia'],['EC','Ecuador'],['PE','Perú'],['VE','Venezuela'],['US','Estados Unidos'],['CA','Canadá'],['MX','México'],['ES','España'],['FR','Francia'],['IT','Italia'],['DE','Alemania'],['GB','Reino Unido'],['PT','Portugal'],['NL','Países Bajos'],['CH','Suiza'],['SE','Suecia'],['NO','Noruega'],['JP','Japón'],['CN','China'],['IN','India'],['AU','Australia'],['NZ','Nueva Zelanda'],['ZA','Sudáfrica'],['IL','Israel'],['AE','Emiratos Árabes Unidos'],['OTHER','Otro país']];
 function setupForm(){const select=document.getElementById('shipCountry');if(!select)return;countries.forEach(([code,name])=>{const o=document.createElement('option');o.value=code;o.textContent=name;select.appendChild(o)});select.value=storedCode();try{const saved=JSON.parse(localStorage.getItem('awsShippingAddress')||'null');if(saved){for(const [k,v] of Object.entries(saved)){const el=document.querySelector(`[name="${k}"]`);if(el)el.value=v}if(saved.fullName&&!saved.firstName&&!saved.lastName){const parts=String(saved.fullName).trim().split(/\s+/);document.getElementById('shipFirstName').value=parts.shift()||'';document.getElementById('shipLastName').value=parts.join(' ')||''}}}catch{}select.addEventListener('change',()=>{countryCode=select.value;localStorage.setItem('awsCountryCode',countryCode);render();updateCheckoutState()});document.getElementById('shippingForm')?.addEventListener('input',updateCheckoutState);document.getElementById('shippingForm')?.addEventListener('change',updateCheckoutState);updateCheckoutState()}
 function requiredShippingValid(){const ids=['shipFirstName','shipLastName','shipCity','shipRegion','shipPostalCode','shipCountry','shipEmail'];return ids.every(id=>{const el=document.getElementById(id);if(!el||!String(el.value||'').trim())return false;if(el.type==='email'&&!el.checkValidity())return false;if(id==='shipCountry'&&el.value==='OTHER')return false;return true})}
 function updateCheckoutState(){const button=document.getElementById('startCheckout');if(!button)return;if(button.dataset.loading==='1')return;button.disabled=cart.length===0;button.textContent='Continuar al pago'}
 function getAddress(){const form=document.getElementById('shippingForm');const data=Object.fromEntries(new FormData(form).entries());data.countryCode=String(data.countryCode||'').toUpperCase();data.fullName=`${String(data.firstName||'').trim()} ${String(data.lastName||'').trim()}`.trim();const requiredIds=['shipFirstName','shipLastName','shipCity','shipRegion','shipPostalCode','shipCountry','shipEmail'];let valid=true;requiredIds.forEach(id=>{const el=document.getElementById(id);const bad=!el||!String(el.value||'').trim()||(el.type==='email'&&!el.checkValidity())||(id==='shipCountry'&&el.value==='OTHER');el?.closest('.shipping-field')?.classList.toggle('invalid',bad);if(bad)valid=false});if(!valid)throw new Error('Completá nombre, apellido, ciudad, provincia, código postal, país y correo electrónico.');localStorage.setItem('awsShippingAddress',JSON.stringify(data));localStorage.setItem('awsCountryCode',data.countryCode);return data}
 async function checkout(){const button=document.getElementById('startCheckout'),errorBox=document.getElementById('checkoutError');errorBox.hidden=true;errorBox.textContent='';if(!cart.length){errorBox.textContent='El carrito está vacío.';errorBox.hidden=false;return}let shippingAddress;try{shippingAddress=getAddress()}catch(e){errorBox.textContent='Debés completar los detalles de envío antes de continuar al pago.';errorBox.hidden=false;const shipping=document.getElementById('shippingDestination');shipping?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.getElementById('shipFirstName')?.focus({preventScroll:true}),450);return}countryCode=shippingAddress.countryCode;foreign=countryCode!=='AR';if(foreign&&(!Number.isFinite(arsPerUsd)||arsPerUsd<=0)){errorBox.textContent='Falta configurar ARS_PER_USD.';errorBox.hidden=false;return}if(foreign&&!paypalConfigured){errorBox.textContent='PayPal no está configurado.';errorBox.hidden=false;return}
 button.disabled=true;button.dataset.loading='1';button.textContent='Preparando pago…';try{const endpoint=foreign?'/api/checkout/paypal':'/api/checkout/mercadopago';const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart,countryCode,shippingAddress})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo iniciar el pago.');location.href=data.checkoutUrl}catch(e){errorBox.textContent=e.message;errorBox.hidden=false;button.dataset.loading='0';updateCheckoutState()}}
 async function init(){setupForm();try{const response=await fetch('/api/store-config',{cache:'no-store'});const config=await response.json();arsPerUsd=Number(config.arsPerUsd);paypalConfigured=Boolean(config.paypalConfigured)}catch{}document.getElementById('startCheckout').onclick=checkout;render();updateCheckoutState()}
 init();
})();
