
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lang=(localStorage.getItem('awsLang')||'es').split('-')[0]; if(!TRAD_T[lang])lang='en';
let selected={}; let priceMode=localStorage.getItem('awsCountry')&&localStorage.getItem('awsCountry')!=='Argentina'?'EXT':'AR';
const money=n=>new Intl.NumberFormat(lang==='es'?'es-AR':lang,{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
function tr(){let t=TRAD_T[lang]; document.documentElement.lang=lang; $$('[data-tr]').forEach(e=>e.textContent=t[e.dataset.tr]||e.textContent); $$('.lang-select').forEach(s=>s.value=lang); renderAll();}
function pprice(p){return priceMode==='AR'?p.priceAR:p.priceEXT}
function renderProducts(){const el=$('#productGrid'); if(!el)return; el.innerHTML=TRAD_PRODUCTS.map(p=>`<article class="product-choice ${selected[p.id]?'selected':''}" data-id="${p.id}"><img src="${p.image}" alt="${p.name}"><h3>${p.name}</h3><div class="price">${money(pprice(p))}</div><div class="small">${TRAD_T[lang][priceMode==='AR'?'arg':'ext']}</div><div class="qty"><button data-op="minus">−</button><b>${selected[p.id]||0}</b><button data-op="plus">+</button><button class="btn" data-op="variant">${TRAD_T[lang].add}</button></div></article>`).join('');}
function renderSummary(){const el=$('#summaryItems');if(!el)return;let rows=[],total=0;for(const [id,q] of Object.entries(selected)){if(!q)continue;let p=TRAD_PRODUCTS.find(x=>x.id===id);let s=pprice(p)*q;total+=s;rows.push(`<div class="sum-row"><span>${q} × ${p.name}</span><b>${money(s)}</b></div>`)}el.innerHTML=rows.join('')||`<p>${TRAD_T[lang].empty}</p>`;$('#summaryTotal').textContent=money(total);$('#minimumState').textContent=total>=500000?'✓ '+TRAD_T[lang].min:'⚠ '+TRAD_T[lang].min;}
function renderCombos(){const el=$('#comboGrid');if(!el)return;el.innerHTML=TRAD_COMBOS.map(c=>{let total=0;let lis=c.items.map(([id,q])=>{let p=TRAD_PRODUCTS.find(x=>x.id===id);total+=pprice(p)*q;return `<li>${q} × ${p.name}</li>`}).join('');return `<article class="combo-card"><div class="small">COMBO ${c.code}</div><h3>${c.name}</h3><ul>${lis}</ul><div class="price">${money(total)}</div><a class="btn" href="productos/tradicion-combo-${c.code}.html">${TRAD_T[lang].details}</a></article>`}).join('')}
function renderAll(){renderProducts();renderSummary();renderCombos()}
function openVariants(id){let p=TRAD_PRODUCTS.find(x=>x.id===id);$('#variantTitle').textContent=p.name;$('#variantGrid').innerHTML=[p.image,p.image,p.image].map((im,i)=>`<div class="variant-card ${i===0?'active':''}" data-id="${id}"><img src="${im}" alt="${p.name}"><p>${TRAD_T[lang].variants} ${i+1}</p></div>`).join('');$('#variantOverlay').classList.add('open')}
document.addEventListener('click',e=>{let card=e.target.closest('.product-choice');if(card){let id=card.dataset.id,op=e.target.dataset.op;if(op==='plus')selected[id]=(selected[id]||0)+1;if(op==='minus')selected[id]=Math.max(0,(selected[id]||0)-1);if(op==='variant')openVariants(id);renderAll()}if(e.target.closest('.variant-card')){let id=e.target.closest('.variant-card').dataset.id;selected[id]=(selected[id]||0)+1;$('#variantOverlay').classList.remove('open');renderAll()}if(e.target.matches('.variant-close')||e.target.id==='variantOverlay')$('#variantOverlay').classList.remove('open')});
document.addEventListener('change',e=>{if(e.target.matches('.lang-select')){lang=e.target.value;localStorage.setItem('awsLang',lang);tr()}if(e.target.id==='priceMode'){priceMode=e.target.value;renderAll()}});
tr();
